image:
  name: alantindale/mybuild:latest

pipelines:
  default:
    - step:
        name: Test version file not changed
        script:
          - git diff --exit-code VERSION

  custom:
    release-inc-patch:
      - step:
          caches:
            - pip
          name: Release current version and increment minor version
          script:
            - /scripts/release.sh patch

    release-inc-minor:
      - step:
          caches:
            - pip
          name: Release current version and increment minor version
          script:
            - /scripts/release.sh minor
    release-inc-major:
      - step:
          caches:
            - pip
          name: Release current version and increment major version
          script:
            - /scripts/release.sh major
